/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/add-details` | `/add-details`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/Qlogout` | `/Qlogout`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/qsign-in` | `/qsign-in`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/qverify` | `/qverify`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}${'/(profile)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}${'/(profile)'}/referral` | `/referral`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}${'/(profile)'}/wallet` | `/wallet`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/add-details` | `/add-details`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/Qlogout` | `/Qlogout`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/qsign-in` | `/qsign-in`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/qverify` | `/qverify`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/home` | `/home`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}${'/(profile)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}${'/(profile)'}/referral` | `/referral`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}${'/(profile)'}/wallet` | `/wallet`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/add-details${`?${string}` | `#${string}` | ''}` | `/add-details${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/Qlogout${`?${string}` | `#${string}` | ''}` | `/Qlogout${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/qsign-in${`?${string}` | `#${string}` | ''}` | `/qsign-in${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/qverify${`?${string}` | `#${string}` | ''}` | `/qverify${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/home${`?${string}` | `#${string}` | ''}` | `/home${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${'/(profile)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${'/(profile)'}/referral${`?${string}` | `#${string}` | ''}` | `/referral${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${'/(profile)'}/wallet${`?${string}` | `#${string}` | ''}` | `/wallet${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/add-details` | `/add-details`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/Qlogout` | `/Qlogout`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/qsign-in` | `/qsign-in`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/qverify` | `/qverify`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}${'/(profile)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}${'/(profile)'}/referral` | `/referral`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}${'/(profile)'}/wallet` | `/wallet`; params?: Router.UnknownInputParams; };
    }
  }
}
